# Site settings
title: all? any? in Ruby
header-img: img/home-bg.png
email: epetushova@gmail.com
copyright_name: PetushovaE
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PetushovaE
learn_profile: PetushovaE
email_username: epetushova@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
